### ISSUE TITLE
How to import `glew`

### ISSUE THREAD

**Issue by GNHua** [conda-forge/glew-feedstock#1]
I am using anaconda on Mac, and have PyOpenGL installed. It works fine. Now I want to install glew. Even though the installation through `conda install glew` is successful, when I `import glew`, I receive error `No module name 'glew'`.

**Comment by dschreij** [comment]
the glew package on Anaconda is the C package only, and it does not provide any python modules. To use it you need an external package such as [GLEWpy](http://glewpy.sourceforge.net/) that interfaces with the C libraries. It is not available on Anaconda (yet?), but you can install it with pip (from pypi):

~~~
pip install glewpy
~~~

**Comment by GNHua** [comment]
When I try `pip install glewpy`, this pops up.
`
Could not find a version that satisfies the requirement glewpy (from versions: )
No matching distribution found for glewpy
`

**Comment by dschreij** [comment]
I just tried the pip install command too and it fails with the same message. After having a look on https://pypi.python.org/pypi/glewpy, I found out that the record on pip does not contain any files anymore that could be downloaded. If you look on sourceforge (https://sourceforge.net/projects/glewpy/files/) you can see that the last update to glewpy was over 10 years ago, so I think that project can be considered dead.

I can't find any other information about python wrappers for GLEW, and I'm not sure if there are any. I'd recommend looking for another, better maintained, library which serves as a windowing toolkit for GL. Have you had a look at PyQt or PySDL2?
